ConstructIT/Controllers/MasinaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConstructIT.DAL;
using ConstructIT.DAL.Models;

namespace ConstructIT.Controllers
{
    public class MasinaController : Controller
    {
        private ConstructITDBContext db = new ConstructITDBContext();

        // GET: Masina
        public async Task<ActionResult> Index(String parametarPretrage)
        {
            IOrderedQueryable<Masina> masine = null;

            if (!String.IsNullOrEmpty(parametarPretrage))
            {
                masine = db.Masine.Include(m => m.TipMasine).Where(m => m.TipMasine.TipMasineNaziv.Contains(parametarPretrage) || m.MasinaProizvodjac.Contains(parametarPretrage)).OrderBy(m => m.TipMasine.TipMasineNaziv);
            }
            else
            {
                masine = db.Masine.Include(m => m.TipMasine).OrderBy(m => m.TipMasine.TipMasineNaziv);
            }


                return View(await masine.ToListAsync());
        }

        // GET: Masina/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Masina masina = await db.Masine.FindAsync(id);
            if (masina == null)
            {
                return HttpNotFound();
            }
            return View(masina);
        }

        // GET: Masina/Create
        public ActionResult Create()
        {
            ViewBag.TipMasineID = new SelectList(db.TipoviMasina, "TipMasineID", "TipMasineNaziv");
            return View();
        }

        // POST: Masina/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MasinaID,MasinaProizvodjac,MasinaOpis,TipMasineID,MasinaDostupnaKolicina")] Masina masina)
        {
            if (ModelState.IsValid)
            {
                db.Masine.Add(masina);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.TipMasineID = new SelectList(db.TipoviMasina, "TipMasineID", "TipMasineNaziv", masina.TipMasineID);
            return View(masina);
        }

        // GET: Masina/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Masina masina = await db.Masine.FindAsync(id);
            if (masina == null)
            {
                return HttpNotFound();
            }
            ViewBag.TipMasineID = new SelectList(db.TipoviMasina, "TipMasineID", "TipMasineNaziv", masina.TipMasineID);
            return View(masina);
        }

        // POST: Masina/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "MasinaID,MasinaProizvodjac,MasinaOpis,TipMasineID,MasinaDostupnaKolicina")] Masina masina)
        {
            if (ModelState.IsValid)
            {
                db.Entry(masina).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.TipMasineID = new SelectList(db.TipoviMasina, "TipMasineID", "TipMasineNaziv", masina.TipMasineID);
            return View(masina);
        }

        // GET: Masina/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Masina masina = await db.Masine.FindAsync(id);
            if (masina == null)
            {
                return HttpNotFound();
            }
            return View(masina);
        }

        // POST: Masina/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Masina masina = await db.Masine.FindAsync(id);
            db.Masine.Remove(masina);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConstructIT/Controllers/ProjekatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConstructIT.DAL;
using ConstructIT.DAL.Models;

namespace ConstructIT.Controllers
{
    public class ProjekatController : Controller
    {
        private ConstructITDBContext db = new ConstructITDBContext();

        // GET: Projekat
        public async Task<ActionResult> Index()
        {
            return View(await db.Projekti.ToListAsync());
        }

        // GET: Projekat/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projekat projekat = await db.Projekti.Include(p => p.Zadaci).Where(p => p.ProjekatID == id).FirstOrDefaultAsync();
            if (projekat == null)
            {
                return HttpNotFound();
            }
            return View(projekat);
        }

        // GET: Projekat/Create
        public ActionResult Create()
        {
            ViewData["korisnici"] = db.Korisnici.Where(k => (k.KorisnikTip == "Klijent" && k.KlijentovProjekatID == null) || k.KorisnikTip == "Tehn. Osoblje").ToList();
            return View();
        }

        // POST: Projekat/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ProjekatID,ProjekatNaziv,ProjekatOpis,ProjekatAdresa,OdabraniKorisnici")] Projekat projekat)
        {

            Projekat p = db.Projekti.Where(pr => pr.ProjekatNaziv == projekat.ProjekatNaziv).FirstOrDefault();

            if(p != null)
            {
                ModelState.AddModelError("ProjekatNaziv", "Već postoji projekat sa unetim nazivom!");
            }

            if (ModelState.IsValid)
            {
                projekat.Korisnici = new List<Korisnik>();
                projekat.Klijenti = new LinkedList<Korisnik>();

                foreach (int korisnikID in projekat.OdabraniKorisnici)
                {
                    projekat.Korisnici.Add(db.Korisnici.Where(k => k.KorisnikID == korisnikID && k.KorisnikTip == "Tehn. Osoblje").FirstOrDefault());

                    projekat.Klijenti.Add(db.Korisnici.Where(k => k.KorisnikID == korisnikID && k.KorisnikTip == "Klijent").FirstOrDefault());
                }

                db.Projekti.Add(projekat);

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(projekat);
        }

        // GET: Projekat/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projekat projekat = await db.Projekti.Where(p => p.ProjekatID == id).Include(p => p.Korisnici).Include(p => p.Klijenti).FirstOrDefaultAsync();
            if (projekat == null)
            {
                return HttpNotFound();
            }
            ViewData["korisnici"] = db.Korisnici.Where(k => (k.KorisnikTip == "Klijent" && k.KlijentovProjekatID == id ) || (k.KorisnikTip == "Klijent" && k.KlijentovProjekatID == null) || k.KorisnikTip == "Tehn. Osoblje").ToList();
            return View(projekat);
        }

        // POST: Projekat/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ProjekatID,ProjekatNaziv,ProjekatOpis,ProjekatAdresa,OdabraniKorisnici")] Projekat projekat)
        {
            Projekat p = db.Projekti.Where(pr => pr.ProjekatNaziv == projekat.ProjekatNaziv && pr.ProjekatID != projekat.ProjekatID).FirstOrDefault();

            if (p != null)
            {
                ModelState.AddModelError("ProjekatNaziv", "Već postoji projekat sa unetim nazivom!");
            }

            if (ModelState.IsValid)
            {
                db.Entry(projekat).State = EntityState.Modified;
                db.SaveChanges();

                Projekat dbProjekat = db.Projekti.Where(pr => pr.ProjekatID == projekat.ProjekatID).Include(pr => pr.Korisnici).Include(pr => pr.Klijenti).FirstOrDefault();
                
                if(dbProjekat.Korisnici == null)
                {
                    dbProjekat.Korisnici = new List<Korisnik>();
                }

                if(dbProjekat.Klijenti == null)
                {
                    dbProjekat.Klijenti = new List<Korisnik>();
                }

                dbProjekat.Korisnici.Clear();
                dbProjekat.Klijenti.Clear();

                foreach (int korisnikID in projekat.OdabraniKorisnici)
                {
                    dbProjekat.Korisnici.Add(db.Korisnici.Where(k => k.KorisnikID == korisnikID && k.KorisnikTip == "Tehn. Osoblje").FirstOrDefault());

                    dbProjekat.Klijenti.Add(db.Korisnici.Where(k => k.KorisnikID == korisnikID && k.KorisnikTip == "Klijent").FirstOrDefault());

                }

                await db.SaveChangesAsync();

                return RedirectToAction("Details", new { id = projekat.ProjekatID });
            }
            return View(projekat);
        }

        // GET: Projekat/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projekat projekat = await db.Projekti.FindAsync(id);
            if (projekat == null)
            {
                return HttpNotFound();
            }
            return View(projekat);
        }

        // POST: Projekat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Projekat projekat = await db.Projekti.FindAsync(id);
            db.Projekti.Remove(projekat);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConstructIT/Controllers/StrukaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConstructIT.DAL;
using ConstructIT.DAL.Models;

namespace ConstructIT.Controllers
{
    public class StrukaController : Controller
    {
        private ConstructITDBContext db = new ConstructITDBContext();

        // GET: Struka
        public async Task<ActionResult> Index()
        {
            return View(await db.Struke.ToListAsync());
        }

        // GET: Struka/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Struka struka = await db.Struke.FindAsync(id);
            if (struka == null)
            {
                return HttpNotFound();
            }
            return View(struka);
        }

        // GET: Struka/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Struka/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "StrukaID,StrukaNaziv")] Struka struka)
        {
            if (ModelState.IsValid)
            {
                db.Struke.Add(struka);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(struka);
        }

        // GET: Struka/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Struka struka = await db.Struke.FindAsync(id);
            if (struka == null)
            {
                return HttpNotFound();
            }
            return View(struka);
        }

        // POST: Struka/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "StrukaID,StrukaNaziv")] Struka struka)
        {
            if (ModelState.IsValid)
            {
                db.Entry(struka).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(struka);
        }

        // GET: Struka/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Struka struka = await db.Struke.FindAsync(id);
            if (struka == null)
            {
                return HttpNotFound();
            }
            return View(struka);
        }

        // POST: Struka/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Struka struka = await db.Struke.FindAsync(id);
            db.Struke.Remove(struka);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConstructIT/Views/Shared/_Layout.cshtml
@using ConstructIT.DAL.Models

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - ConstructIT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

    <script type="text/javascript" src="@Url.Content("/Scripts/jquery-1.10.2.js")"></script>
    @RenderSection("JavaScript", required: false)

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ConstructIT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        Korisnik korisnik = (Korisnik)Session["korisnik"];

                        String korisnikTip = "";

                        if (korisnik != null)
                        {
                            korisnikTip = korisnik.KorisnikTip;
                        }

                    }

                    @if (korisnikTip != "" && korisnikTip != "Klijent")
                    {
                        <li>@Html.ActionLink("Početna stranica", "Index", "Home")</li>
                        <li>@Html.ActionLink("Projekti", "Index", "Projekat")</li>
                    }




                    @if (korisnikTip == "Administrator")
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Resursi <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Proizvodni radnici", "Index", "ProizvodniRadnik")</li>
                                <li>@Html.ActionLink("Mašine", "Index", "Masina")</li>
                                <li>@Html.ActionLink("Materijali", "Index", "Materijal")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Struke", "Index", "Struka")</li>
                                <li>@Html.ActionLink("Tipovi Mašina", "Index", "TipMasine")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Potrebe za resursima <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Potrebe struka", "Index", "PotrebaStruke")</li>
                                <li>@Html.ActionLink("Potrebe tipova mašina", "Index", "PotrebaTipaMasine")</li>
                                <li>@Html.ActionLink("Potrebe materijala", "Index", "PotrebaMaterijala")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Raspodela resursa<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Evidencija radnog vremena", "Index", "EvidencijaRadnogVremena")</li>
                                <li>@Html.ActionLink("Evidencija angažovanja mašine", "Index", "EvidencijaAngazovanjaMasine")</li>
                                <li>@Html.ActionLink("Dodela materijala", "Index", "DodelaMaterijala")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Izveštaji <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Proizvodni radnici", "Index", "ProizvodniRadnik")</li>
                                <li>@Html.ActionLink("Mašine", "Index", "Masina")</li>
                                <li>@Html.ActionLink("Materijali", "Index", "Materijal")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Struke", "Index", "Struka")</li>
                                <li>@Html.ActionLink("Tipovi Mašina", "Index", "TipMasine")</li>
                            </ul>
                        </li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ConstructIT</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>