ConstructIT/Controllers/ProizvodniRadnikController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConstructIT.DAL;
using ConstructIT.DAL.Models;

namespace ConstructIT.Controllers
{
    public class ProizvodniRadnikController : Controller
    {
        private ConstructITDBContext db = new ConstructITDBContext();

        // GET: ProizvodniRadnik
        public async Task<ActionResult> Index(String parametarPretrage)
        {
            var proizvodniRadnici = db.ProizvodniRadnici.Include(p => p.Struka);

            if (!String.IsNullOrEmpty(parametarPretrage))
            {
                proizvodniRadnici = proizvodniRadnici.Where(pr => pr.Struka.StrukaNaziv.Contains(parametarPretrage) || pr.ProizRadIme.Contains(parametarPretrage) || pr.ProizRadPrezime.Contains(parametarPretrage) || pr.ProizvodniRadnikID.ToString() == parametarPretrage);
            }

            
            return View(await proizvodniRadnici.ToListAsync());
        }

        // GET: ProizvodniRadnik/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProizvodniRadnik proizvodniRadnik = await db.ProizvodniRadnici.FindAsync(id);
            if (proizvodniRadnik == null)
            {
                return HttpNotFound();
            }
            return View(proizvodniRadnik);
        }

        // GET: ProizvodniRadnik/Create
        public ActionResult Create()
        {
            ViewBag.StrukaID = new SelectList(db.Struke, "StrukaID", "StrukaNaziv");
            return View();
        }

        // POST: ProizvodniRadnik/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ProizvodniRadnikID,ProizRadJMBG,ProizRadIme,ProizRadPrezime,ProizRadEMail,ProizRadAdresa,ProizRadTelMob,StrukaID")] ProizvodniRadnik proizvodniRadnik)
        {
            if (ModelState.IsValid)
            {
                db.ProizvodniRadnici.Add(proizvodniRadnik);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.StrukaID = new SelectList(db.Struke, "StrukaID", "StrukaNaziv", proizvodniRadnik.StrukaID);
            return View(proizvodniRadnik);
        }

        // GET: ProizvodniRadnik/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProizvodniRadnik proizvodniRadnik = await db.ProizvodniRadnici.FindAsync(id);
            if (proizvodniRadnik == null)
            {
                return HttpNotFound();
            }
            ViewBag.StrukaID = new SelectList(db.Struke, "StrukaID", "StrukaNaziv", proizvodniRadnik.StrukaID);
            return View(proizvodniRadnik);
        }

        // POST: ProizvodniRadnik/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ProizvodniRadnikID,ProizRadJMBG,ProizRadIme,ProizRadPrezime,ProizRadEMail,ProizRadAdresa,ProizRadTelMob,StrukaID")] ProizvodniRadnik proizvodniRadnik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proizvodniRadnik).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.StrukaID = new SelectList(db.Struke, "StrukaID", "StrukaNaziv", proizvodniRadnik.StrukaID);
            return View(proizvodniRadnik);
        }

        // GET: ProizvodniRadnik/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProizvodniRadnik proizvodniRadnik = await db.ProizvodniRadnici.FindAsync(id);
            if (proizvodniRadnik == null)
            {
                return HttpNotFound();
            }
            return View(proizvodniRadnik);
        }

        // POST: ProizvodniRadnik/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ProizvodniRadnik proizvodniRadnik = await db.ProizvodniRadnici.FindAsync(id);
            db.ProizvodniRadnici.Remove(proizvodniRadnik);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConstructIT/Views/ProizvodniRadnik/Create.cshtml
@model ConstructIT.DAL.Models.ProizvodniRadnik

@{
    ViewBag.Title = "Kreiranje proizvodnog radnika";
}

<h2>Kreiraj</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="padding-left: 3%">Proizvodni radnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadJMBG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadJMBG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadJMBG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadIme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadIme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadIme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadPrezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadPrezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadPrezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadEMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadEMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadEMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadAdresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadAdresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadAdresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadTelMob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadTelMob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadTelMob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrukaID, "StrukaID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StrukaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StrukaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Odustani", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConstructIT/Views/ProizvodniRadnik/Delete.cshtml
@model ConstructIT.DAL.Models.ProizvodniRadnik

@{
    ViewBag.Title = "Brisanje proizvodnog radnika";
}

<h2>Brisanje</h2>

<h3 style="padding-left: 3%">Da li ste sigurni da želite da obrišete?</h3>
<div>
    <hr />
    <h4>Proizvodni radnik</h4>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Struka.StrukaNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Struka.StrukaNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadJMBG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadJMBG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadIme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadIme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadPrezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadPrezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadEMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadEMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadAdresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadAdresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadTelMob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadTelMob)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Odustani", "Index")
        </div>
    }
</div>

ConstructIT/Views/ProizvodniRadnik/Details.cshtml
@model ConstructIT.DAL.Models.ProizvodniRadnik

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProizvodniRadnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Struka.StrukaNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Struka.StrukaNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadJMBG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadJMBG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadIme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadIme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadPrezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadPrezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadEMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadEMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadAdresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadAdresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProizRadTelMob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProizRadTelMob)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProizvodniRadnikID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ConstructIT/Views/ProizvodniRadnik/Edit.cshtml
@model ConstructIT.DAL.Models.ProizvodniRadnik

@{
    ViewBag.Title = "Izmena proizvodnog radnika";
}

<h2>Izmena</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="padding-left: 3%">Proizvodni radnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProizvodniRadnikID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadJMBG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadJMBG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadJMBG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadIme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadIme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadIme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadPrezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadPrezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadPrezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadEMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadEMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadEMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadAdresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadAdresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadAdresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProizRadTelMob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProizRadTelMob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProizRadTelMob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StrukaID, "StrukaID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StrukaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StrukaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sačuvaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Odustani", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConstructIT/Views/ProizvodniRadnik/Index.cshtml
@model IEnumerable<ConstructIT.DAL.Models.ProizvodniRadnik>

@{
    ViewBag.Title = "Proizvodni radnici";
}

<h2>Proizvodni radnici</h2>

<p>
    @Html.ActionLink("Dodaj novog", "Create")
</p>


@using (Html.BeginForm("Index", "ProizvodniRadnik", FormMethod.Post, new { @class = "searchForm form-inline" }))
{
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control input-sm" placeholder="Pretraga..." name="parametarPretrage" value="">
            <span class="input-group-btn">
                <button class="btn btn-success btn-sm" type="submit">Pretraži</button>
            </span>
        </div>
    </div>
}

<hr />

<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProizvodniRadnikID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Struka.StrukaNaziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProizRadIme)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProizRadPrezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProizRadJMBG)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProizRadEMail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProizRadAdresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProizRadTelMob)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProizvodniRadnikID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Struka.StrukaNaziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProizRadIme)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProizRadPrezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProizRadJMBG)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProizRadEMail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProizRadAdresa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProizRadTelMob)
        </td>
        <td>
            @Html.ActionLink("Izmeni", "Edit", new { id=item.ProizvodniRadnikID }) |
            @Html.ActionLink("Obriši", "Delete", new { id=item.ProizvodniRadnikID })
        </td>
    </tr>
}

</table>