ConstructIT/Controllers/PotrebaMaterijalaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConstructIT.DAL;
using ConstructIT.DAL.Models;

namespace ConstructIT.Controllers
{
    public class PotrebaMaterijalaController : Controller
    {
        private ConstructITDBContext db = new ConstructITDBContext();

        // GET: PotrebaMaterijala
        public async Task<ActionResult> Index()
        {
            DateTime today = DateTime.Today;

            var potrebeMaterijala = db.PotrebeMaterijala.Where(pm => pm.PotrMatKolicina > 0 && DbFunctions.TruncateTime(pm.PotrMatOdDatuma) <= today && DbFunctions.TruncateTime(pm.PotrMatDoDatuma) >= today).Include(p => p.Materijal).Include(p => p.Zadatak);
            return View(await potrebeMaterijala.ToListAsync());
        }

        // GET: PotrebaMaterijala/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PotrebaMaterijala potrebaMaterijala = await db.PotrebeMaterijala.FindAsync(id);
            if (potrebaMaterijala == null)
            {
                return HttpNotFound();
            }
            return View(potrebaMaterijala);
        }

        // GET: PotrebaMaterijala/Create
        public ActionResult Create(int projekatID, int zadatakID)
        {
            ViewBag.MaterijalID = new SelectList(db.Materijali.OrderBy(m => m.MaterijalNaziv), "MaterijalID", "MaterijalNaziv");
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == projekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == zadatakID).FirstOrDefault().ZadatakNaziv;
            ViewBag.ProjekatID = projekatID;
            ViewBag.ZadatakID = zadatakID;
            return View();
        }

        // POST: PotrebaMaterijala/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ProjekatID,ZadatakID,MaterijalID,PotrMatOdDatuma,PotrMatDoDatuma,PotrMatKolicina")] PotrebaMaterijala potrebaMaterijala)
        {
            if (ModelState.IsValid)
            {
                db.PotrebeMaterijala.Add(potrebaMaterijala);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Zadatak", new { id = potrebaMaterijala.ZadatakID });
            }

            ViewBag.MaterijalID = new SelectList(db.Materijali.OrderBy(m => m.MaterijalNaziv), "MaterijalID", "MaterijalNaziv", potrebaMaterijala.MaterijalID);
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == potrebaMaterijala.ProjekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == potrebaMaterijala.ZadatakID).FirstOrDefault().ZadatakNaziv;
            ViewBag.ProjekatID = potrebaMaterijala.ProjekatID;
            ViewBag.ZadatakID = potrebaMaterijala.ZadatakID;
            return View(potrebaMaterijala);
        }

        // GET: PotrebaMaterijala/Edit/5
        public async Task<ActionResult> Edit(int? PotrebaMaterijalaID)
        {
            if (PotrebaMaterijalaID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PotrebaMaterijala potrebaMaterijala = await db.PotrebeMaterijala.FindAsync(PotrebaMaterijalaID);
            if (potrebaMaterijala == null)
            {
                return HttpNotFound();
            }

            ViewBag.MaterijalNaziv = db.Materijali.Where(m => m.MaterijalID == potrebaMaterijala.MaterijalID).FirstOrDefault().MaterijalNaziv;
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == potrebaMaterijala.ProjekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == potrebaMaterijala.ZadatakID).FirstOrDefault().ZadatakNaziv;

            return View(potrebaMaterijala);
        }

        // POST: PotrebaMaterijala/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PotrebaMaterijalaID,ProjekatID,ZadatakID,MaterijalID,PotrMatOdDatuma,PotrMatDoDatuma,PotrMatKolicina")] PotrebaMaterijala potrebaMaterijala)
        {
            if (ModelState.IsValid)
            {
                db.Entry(potrebaMaterijala).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Zadatak", new { id = potrebaMaterijala.ZadatakID });
            }

            ViewBag.MaterijalNaziv = db.Materijali.Where(m => m.MaterijalID == potrebaMaterijala.MaterijalID).FirstOrDefault().MaterijalNaziv;
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == potrebaMaterijala.ProjekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == potrebaMaterijala.ZadatakID).FirstOrDefault().ZadatakNaziv;

            return View(potrebaMaterijala);
        }

        // GET: PotrebaMaterijala/Delete/5
        public async Task<ActionResult> Delete(int potrebaMaterijalaID)
        {
            PotrebaMaterijala potrebaMaterijala = await db.PotrebeMaterijala.Where(p => p.PotrebaMaterijalaID == potrebaMaterijalaID).FirstOrDefaultAsync();
            if (potrebaMaterijala == null)
            {
                return HttpNotFound();
            }
            return View(potrebaMaterijala);
        }

        // POST: PotrebaMaterijala/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int potrebaTipaMaterijalaID)
        {
            PotrebaMaterijala potrebaMaterijala = await db.PotrebeMaterijala.Where(p => p.PotrebaMaterijalaID == potrebaTipaMaterijalaID).FirstOrDefaultAsync();
            db.PotrebeMaterijala.Remove(potrebaMaterijala);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Zadatak", new { id = potrebaMaterijala.ZadatakID });
        }

        public async Task<ActionResult> AutoAssignMaterial()
        {
            await db.Database.ExecuteSqlCommandAsync("PR_AUTO_ASSIGN_MATERIAL");

            return RedirectToAction("Index", "DodelaMaterijala");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConstructIT/Views/PotrebaMaterijala/Create.cshtml
@model ConstructIT.DAL.Models.PotrebaMaterijala
@using ConstructIT.DAL.Models

@{
    ViewBag.Title = "Kreiranje potrebe materijala";

    var _projekat = new Projekat();
    var _zadatak = new Zadatak();
}

<h2>Kreiranje</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="padding-left: 3%">Potreba materijala</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => _projekat.ProjekatNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ProjekatNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => _zadatak.ZadatakNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ZadatakNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaterijalID, "Materijal", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaterijalID", null, htmlAttributes: new { @class = "form-control selectpicker col-md-10" })
                @Html.ValidationMessageFor(model => model.MaterijalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrMatOdDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrMatOdDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrMatOdDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrMatDoDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrMatDoDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrMatDoDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrMatKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrMatKolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrMatKolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ProjekatID, new { Value = ViewBag.ProjekatID })
        @Html.HiddenFor(model => model.ZadatakID, new { Value = ViewBag.ZadatakID })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="@Url.Content("/Scripts/bootstrap-select.js")"></script>
    <script type="text/javascript" src="@Url.Content("/Scripts/search-select-init.js")"></script>
}

@section Styles{
    <link rel="Stylesheet" href="@Href("~/Content/select-width.css")" />
}

ConstructIT/Views/PotrebaMaterijala/Delete.cshtml
@model ConstructIT.DAL.Models.PotrebaMaterijala

@{
    ViewBag.Title = "Brisanje potrebe materijala";
}

<h2>Brisanje</h2>

<h3 style="padding-left: 3%">Da li ste sigurni da želite da obrišete?</h3>
<div>

    <hr />
    <h4>Potreba materijala</h4>
    <br />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Materijal.MaterijalNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materijal.MaterijalNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zadatak.ZadatakNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zadatak.ZadatakNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrMatOdDatuma)
        </dt>

        <dd>
            @Model.PotrMatOdDatuma.ToString("dd.MM.yyyy.")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrMatDoDatuma)
        </dt>

        <dd>
            @Model.PotrMatDoDatuma.ToString("dd.MM.yyyy.")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrMatKolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PotrMatKolicina)
        </dd>

    </dl>

    @using (Html.BeginForm( new { potrebaTipaMaterijalaID = Model.PotrebaMaterijalaID } )) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Odustani", "Details", "Zadatak", new { id = Model.ZadatakID }, null)
        </div>
    }
</div>

ConstructIT/Views/PotrebaMaterijala/Details.cshtml
@model ConstructIT.DAL.Models.PotrebaMaterijala

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PotrebaMaterijala</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Materijal.MaterijalNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materijal.MaterijalNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zadatak.ZadatakNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zadatak.ZadatakNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrMatKolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PotrMatKolicina)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ConstructIT/Views/PotrebaMaterijala/Edit.cshtml
@model ConstructIT.DAL.Models.PotrebaMaterijala
@using ConstructIT.DAL.Models

@{
    ViewBag.Title = "Izmena potrebe materijala";

    var _projekat = new Projekat();
    var _zadatak = new Zadatak();
}

<h2>Izmena</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4  style="padding-left: 3%">Potreba materijala</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => _projekat.ProjekatNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ProjekatNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => _zadatak.ZadatakNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ZadatakNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Materijal.MaterijalNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.MaterijalNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrMatOdDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrMatOdDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrMatOdDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrMatDoDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrMatDoDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrMatDoDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrMatKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrMatKolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrMatKolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.PotrebaMaterijalaID)
        @Html.HiddenFor(model => model.ProjekatID)
        @Html.HiddenFor(model => model.ZadatakID)
        @Html.HiddenFor(model => model.MaterijalID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sačuvaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ConstructIT/Views/PotrebaMaterijala/Index.cshtml
@model IEnumerable<ConstructIT.DAL.Models.PotrebaMaterijala>

@{
    ViewBag.Title = "Potrebe materijala";
}

<h2>Potrebe materijala</h2>
@Html.ActionLink("Automatski dodeli za današnji dan", "AutoAssignMaterial", "PotrebaMaterijala")
<hr />

<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Materijal.MaterijalNaziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zadatak.ZadatakNaziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PotrMatOdDatuma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PotrMatDoDatuma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PotrMatKolicina)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Materijal.MaterijalNaziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zadatak.ZadatakNaziv)
        </td>
        <th>
            @item.PotrMatOdDatuma.ToString("dd.MM.yyyy.")
        </th>
        <th>
            @item.PotrMatDoDatuma.ToString("dd.MM.yyyy.")
        </th>
        <td>
            @Html.DisplayFor(modelItem => item.PotrMatKolicina)
        </td>
        <td>@Html.ActionLink("Dodeli", "Create", "DodelaMaterijala", new { potrebaMaterijalaID = item.PotrebaMaterijalaID }, null)</td>
    </tr>
}

</table>