ConstructIT/Controllers/PotrebaTipaMasineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConstructIT.DAL;
using ConstructIT.DAL.Models;

namespace ConstructIT.Controllers
{
    public class PotrebaTipaMasineController : Controller
    {
        private ConstructITDBContext db = new ConstructITDBContext();

        // GET: PotrebaTipaMasine
        public async Task<ActionResult> Index()
        {
            DateTime today = DateTime.Today;

            var potrebeTipovaMasina = db.PotrebeTipovaMasina.Include(p => p.TipMasine).Include(p => p.Zadatak).Where(ptm => DbFunctions.TruncateTime(ptm.PotrTipaMasOdDatuma) <= today && DbFunctions.TruncateTime(ptm.PotrTipaMasDoDatuma) >= today);
            return View(await potrebeTipovaMasina.ToListAsync());
        }

        // GET: PotrebaTipaMasine/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PotrebaTipaMasine potrebaTipaMasine = await db.PotrebeTipovaMasina.FindAsync(id);
            if (potrebaTipaMasine == null)
            {
                return HttpNotFound();
            }
            return View(potrebaTipaMasine);
        }

        // GET: PotrebaTipaMasine/Create
        public ActionResult Create(int projekatID, int zadatakID)
        {
            ViewBag.TipMasineID = new SelectList(db.TipoviMasina.OrderBy(tm => tm.TipMasineNaziv), "TipMasineID", "TipMasineNaziv");
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == projekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == zadatakID).FirstOrDefault().ZadatakNaziv;
            ViewBag.ProjekatID = projekatID;
            ViewBag.ZadatakID = zadatakID;
            return View();
        }

        // POST: PotrebaTipaMasine/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PotrebaTipaMasineID,PotrTipaMasOdDatuma,PotrTipaMasDoDatuma,PotrTipaMasKolicina,ProjekatID,ZadatakID,TipMasineID")] PotrebaTipaMasine potrebaTipaMasine)
        {
            if (ModelState.IsValid)
            {
                db.PotrebeTipovaMasina.Add(potrebaTipaMasine);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Zadatak", new { id = potrebaTipaMasine.ZadatakID });
            }

            ViewBag.TipMasineID = new SelectList(db.TipoviMasina.OrderBy(tm => tm.TipMasineNaziv), "TipMasineID", "TipMasineNaziv", potrebaTipaMasine.TipMasineID);
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == potrebaTipaMasine.ProjekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == potrebaTipaMasine.ZadatakID).FirstOrDefault().ZadatakNaziv;
            ViewBag.ProjekatID = potrebaTipaMasine.ProjekatID;
            ViewBag.ZadatakID = potrebaTipaMasine.ZadatakID;
            return View(potrebaTipaMasine);
        }

        // GET: PotrebaTipaMasine/Edit/5
        public async Task<ActionResult> Edit(int? potrebaTipaMasineID)
        {
            if (potrebaTipaMasineID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PotrebaTipaMasine potrebaTipaMasine = await db.PotrebeTipovaMasina.FindAsync(potrebaTipaMasineID);
            if (potrebaTipaMasine == null)
            {
                return HttpNotFound();
            }

            ViewBag.TipMasineNaziv = db.TipoviMasina.Where(t => t.TipMasineID == potrebaTipaMasine.TipMasineID).FirstOrDefault().TipMasineNaziv;
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == potrebaTipaMasine.ProjekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == potrebaTipaMasine.ZadatakID).FirstOrDefault().ZadatakNaziv;

            return View(potrebaTipaMasine);
        }

        // POST: PotrebaTipaMasine/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PotrebaTipaMasineID,PotrTipaMasOdDatuma,PotrTipaMasDoDatuma,PotrTipaMasKolicina,ProjekatID,ZadatakID,TipMasineID")] PotrebaTipaMasine potrebaTipaMasine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(potrebaTipaMasine).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Zadatak", new { id = potrebaTipaMasine.ZadatakID });
            }

            ViewBag.TipMasineNaziv = db.TipoviMasina.Where(t => t.TipMasineID == potrebaTipaMasine.TipMasineID).FirstOrDefault().TipMasineNaziv;
            ViewBag.ProjekatNaziv = db.Projekti.Where(p => p.ProjekatID == potrebaTipaMasine.ProjekatID).FirstOrDefault().ProjekatNaziv;
            ViewBag.ZadatakNaziv = db.Zadaci.Where(z => z.ZadatakID == potrebaTipaMasine.ZadatakID).FirstOrDefault().ZadatakNaziv;

            return View(potrebaTipaMasine);
        }

        // GET: PotrebaTipaMasine/Delete/5
        public async Task<ActionResult> Delete(int? potrebaTipaMasineID)
        {
            if (potrebaTipaMasineID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PotrebaTipaMasine potrebaTipaMasine = await db.PotrebeTipovaMasina.FindAsync(potrebaTipaMasineID);
            if (potrebaTipaMasine == null)
            {
                return HttpNotFound();
            }
            return View(potrebaTipaMasine);
        }

        // POST: PotrebaTipaMasine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            PotrebaTipaMasine potrebaTipaMasine = await db.PotrebeTipovaMasina.FindAsync(id);
            db.PotrebeTipovaMasina.Remove(potrebaTipaMasine);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Zadatak", new { id = potrebaTipaMasine.ZadatakID });
        }

        public async Task<ActionResult> AutoAssignMachines()
        {
            await db.Database.ExecuteSqlCommandAsync("PR_AUTO_ASSIGN_MACHINES");

            return RedirectToAction("Index", "EvidencijaRadnogVremena");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConstructIT/Views/PotrebaTipaMasine/Create.cshtml
@model ConstructIT.DAL.Models.PotrebaTipaMasine
@using ConstructIT.DAL.Models

@{
    ViewBag.Title = "Kreiranje potrebe tipa mašine";

    var _projekat = new Projekat();
    var _zadatak = new Zadatak();
}

<h2>Kreiraj</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4  style="padding-left: 3%">Potreba tipa mašine</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => _projekat.ProjekatNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ProjekatNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => _zadatak.ZadatakNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ZadatakNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipMasineID, "Tip Mašine", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipMasineID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipMasineID, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PotrTipaMasOdDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrTipaMasOdDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrTipaMasOdDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrTipaMasDoDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrTipaMasDoDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrTipaMasDoDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrTipaMasKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrTipaMasKolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrTipaMasKolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ProjekatID, new { Value = ViewBag.ProjekatID })
        @Html.HiddenFor(model => model.ZadatakID, new { Value = ViewBag.ZadatakID })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ConstructIT/Views/PotrebaTipaMasine/Delete.cshtml
@model ConstructIT.DAL.Models.PotrebaTipaMasine

@{
    ViewBag.Title = "Brisanje potrebe tipa mašine";
}

<h2>Brisanje</h2>

<h3 style="padding-left: 3%">Da li ste sigurni da želite da obrišete?</h3>
<div>
    <h4>Potreba tipa mašine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipMasine.TipMasineNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipMasine.TipMasineNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zadatak.ZadatakNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zadatak.ZadatakNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrTipaMasOdDatuma)
        </dt>

        <dd>
            @Model.PotrTipaMasOdDatuma.ToString("dd.MM.yyyy.")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrTipaMasDoDatuma)
        </dt>

        <dd>
            @Model.PotrTipaMasDoDatuma.ToString("dd.MM.yyyy.")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrTipaMasKolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PotrTipaMasKolicina)
        </dd>

    </dl>

    @using (Html.BeginForm(new { id = Model.PotrebaTipaMasineID })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Odustani", "Details", "Zadatak", new { id = Model.ZadatakID }, null)
        </div>
    }
</div>

ConstructIT/Views/PotrebaTipaMasine/Details.cshtml
@model ConstructIT.DAL.Models.PotrebaTipaMasine

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PotrebaTipaMasine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipMasine.TipMasineNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipMasine.TipMasineNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zadatak.ZadatakNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zadatak.ZadatakNaziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrTipaMasOdDatuma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PotrTipaMasOdDatuma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrTipaMasDoDatuma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PotrTipaMasDoDatuma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PotrTipaMasKolicina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PotrTipaMasKolicina)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PotrebaTipaMasineID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ConstructIT/Views/PotrebaTipaMasine/Edit.cshtml
@model ConstructIT.DAL.Models.PotrebaTipaMasine
@using ConstructIT.DAL.Models

@{
    ViewBag.Title = "Izmena potrebe tipa mašine";

    var _projekat = new Projekat();
    var _zadatak = new Zadatak();
}

<h2>Izmena</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4  style="padding-left: 3%">Potreba tipa mašine</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => _projekat.ProjekatNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ProjekatNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => _zadatak.ZadatakNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.ZadatakNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipMasine.TipMasineNaziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.TipMasineNaziv" disabled class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrTipaMasOdDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrTipaMasOdDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrTipaMasOdDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrTipaMasDoDatuma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrTipaMasDoDatuma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrTipaMasDoDatuma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotrTipaMasKolicina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotrTipaMasKolicina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotrTipaMasKolicina, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.PotrebaTipaMasineID)
        @Html.HiddenFor(model => model.ProjekatID)
        @Html.HiddenFor(model => model.ZadatakID)
        @Html.HiddenFor(model => model.TipMasineID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sačuvaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ConstructIT/Views/PotrebaTipaMasine/Index.cshtml
@model IEnumerable<ConstructIT.DAL.Models.PotrebaTipaMasine>

@{
    ViewBag.Title = "Potrebe tipova mašina";
}

<h2>Potrebe tipova mašina</h2>

@Html.ActionLink("Automatski dodeli za današnji dan", "AutoAssignMachines", "PotrebaTipaMasine")
<hr />

<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TipMasine.TipMasineNaziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zadatak.Projekat.ProjekatNaziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zadatak.ZadatakNaziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PotrTipaMasOdDatuma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PotrTipaMasDoDatuma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PotrTipaMasKolicina)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TipMasine.TipMasineNaziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zadatak.Projekat.ProjekatNaziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zadatak.ZadatakNaziv)
        </td>
        <td>
            @item.PotrTipaMasOdDatuma.ToString("dd.MM.yyyy.")
        </td>
        <td>
            @item.PotrTipaMasDoDatuma.ToString("dd.MM.yyyy.")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PotrTipaMasKolicina)
        </td>
    </tr>
}

</table>